### ISSUE TITLE
[FEATURE] DB 서버 배포하기

### ISSUE THREAD

**Issue by J-1ac** [kakao-tech-campus-2nd-step3/Team11_BE#8]
## 기능 설명 
    MS Azure Database for MySQL을 활용해 DB 서버를 배포하고 연결한다.
    
## 마감 일자
    09월 27일까지

## TODO
- [x] MS Azure Database for MySQL 배포하기
- [ ] 연결하기

**Comment by J-1ac** [comment]
회의를 통해 db 배포는 추후로 미루기로 해서 일단 이슈 닫겠습니다~

**Comment by jinseohyun1228** [comment]
구현감사합니다! @J-1ac
